### ISSUE TITLE
Exceptions / warnings conflicting with Jenkin builds

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#126]
Making this ticket per our conversation:

> Evan Krambuhl [2:07 PM]  
> can you open an issue for this?  The second 2 is related to pageroot component rendering an html tag inside of another html tag

`Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <Rhythm>.`

And

`ValidDOMNesting(...) <html> cannot appear as a child of <div>. See StatelessComponent > StatelessComponent > div > PageRoot > PageRoot__Wrapper > html`

**Comment by drolsen** [comment]
Any updates around this? 
Our project has QA blocker I guess cause Jenkins can't get past a build.

**Comment by kamsar** [comment]
`Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <Rhythm>` is because in React when you iterate (e.g. with `prop.map(item => <Foo {...item} />)` the child components are expected to have a `key` attribute added to them. This doesn't really matter for React static rendering (it's so it can patch the DOM more efficiently/accurately when you change the props later).

It also won't fail your build, it's just a warning.

I'd guess the other error is the real culprit.

**Comment by JeffDarchuk** [comment]
according to Xtoff this was fixed here https://github.com/connectivedx/fuzzy-chainsaw/issues/120

**Comment by drolsen** [comment]
This is no longer a blocker for our project, the actual build issue was not related to this warning but rather was related to according to #120. Down grading this to enhancement as these are truly just warnings now.

**Comment by krambuhl** [comment]
This should be fixed in develop now.
