### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval'

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#129]
We've got our dev up and builds going (https://ihn.connectivedx.com/), however our compiled scripts.js is not being accepted by browsers due to CSP error:

> scripts.js:1 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'unsafe-inline' 'self'".

I've tried taking scripts.jsx down to just the basics:

```
require('./tags/PageRoot/PageRoot.css');
require.context("./tags/", true, /\.css$/);
require.context("./components/", true, /\.css$/);
```

But error remains. Possible reasons is cshtml files live within each /component and is getting added to script.js's large eval, but not knowing enough about how webpack should be bundling this I'm unsure.

**Comment by krambuhl** [comment]
If this is happening while running `npm run production`, this is related to devtools option in webpack. (#120 looks like our sourcemaps are the issue).  Try changing this line https://github.com/connectivedx/fuzzy-chainsaw/blob/develop/webpack.production.config.js#L19 to:

```
  config.devtool = '';
```

instead of deleting the line entirely.

**Comment by krambuhl** [comment]
The error is related to `eval('codecodecode')` in https://ihn.connectivedx.com/project.ihn/assets/assets/scripts.js

**Comment by drolsen** [comment]
This seems to be working now.
Would you like me to make a new ticket or is there one already open for soucemaps?

**Comment by blipson89** [comment]
@drolsen @krambuhl @kamsar 

This is still an issue when running `npm run build`. Since `lp build` in Legendary Pancake projects builds off of `npm run build` instead of `npm run production`, this causes issues for active back-end development. 

Is it possible to turn off the evals across the board like in the `production` task?

**Comment by krambuhl** [comment]
The FC codebase has already been updated to use `{ devtools: 'source-map' }` in the build config.  Either your project codebase has not been updated with the latest code, or you are running into a new error.

**Comment by blipson89** [comment]
@krambuhl i did a text-search for my entire solution for `devtools` and it didn't come up with any results. I also tried the same search in this repo and didn't find anything. Could you point me at the commit and/or file so I can verify that we're up to date?

Just to make sure we're on the same page, when I run `npm run build`, I'm seeing:
![image](https://cloud.githubusercontent.com/assets/4602966/22150232/f356d6a0-dee5-11e6-9720-2708899c8e8c.png)

when I run `npm run production`, I see: 
![image](https://cloud.githubusercontent.com/assets/4602966/22150288/3aa09d7a-dee6-11e6-95f1-42a6c8e1cf7c.png)

This is NOT the expected outcome, correct?

**Comment by blipson89** [comment]
@krambuhl nevermind. it was "devtool" and my branch was out of date. everything looks good now
