### ISSUE TITLE
What's buggin' you?

### ISSUE THREAD

**Issue by krambuhl** [connectivedx/fuzzy-chainsaw#138]
@drolsen @pgregorova @stoff @elseloop @nicmarson @kamsar @speeQr 

Hello good folks.  If you've already started a project using Fuzzy Chainsaw, you've probably found some workflow issues or daily annoyances.   I'd like to open up this ticket to discuss ongoing improvements that could be made to remove development friction. 

Some examples I've found so far:

- I'd like to be able to create an example with a dark background in the style guide.  (lead to #136)
- In practice, it seems like using PascalCase in css to match JSX style might be an easier mental model to consume.

**Comment by elseloop** [comment]
(I raised this question on a PR, so I'm just going to copy/paste it in here with some fuzzy context:)

I'm wondering if writing components differently might be easier to read and reason about when passing in props and setting up defaults. I’d like to see us using [`Component.defaultProps`](https://facebook.github.io/react/docs/react-component.html#defaultprops) rather than passing them in individually and setting up defaults in the param declaration (which I'm finding to be noisy and hard to scan). For example, rather than:

```js
const Wrapper = ({
	tagName = 'div',
	size = 'default',
	className = '',
	children
}) => {
	const Tag = tagName;

	return (
		<Tag className={`wrapper wrapper--${size} ${className}`}>
			{children}
		</Tag>
	)
};
```

we could instead write that:

```js
const Wrapper = (props) => {
    const { tagname:Tag, size, className, children } = props;

    return (
        <Tag className={`wrapper wrapper--${size} ${className}`}>
            {children}
        </Tag>
    )
}

Wrapper.defaultProps = {
    tagName = 'div',
    size = 'default'
}
```

This is a matter of style, I know, but having something explicitly called out as defaultProps, which is part of the framework already, and cleaning up the entry point into the component with some more straightforward destructuring strikes me as easier to read and understand.

**Comment by elseloop** [comment]
@krambuhl [I also like the idea of PascalCase CSS selectors](https://github.com/connectivedx/fuzzy-chainsaw/issues/70#issuecomment-257393310). 👍

**Comment by elseloop** [comment]
When you run `npm run new-{tag,component} Whatever`, the resulting `Whatever.jsx` file is written with four space _tabs_. Our `.editorconfig` asks for two _actual spaces_ in `.jsx` files. The result is working in a mixed tab/spaces environment right from the jump. We should remedy this.

**Comment by krambuhl** [comment]
The way we are now building stylesheets, it really isn't required to import stylesheet files into our jsx  component.  all css can be grabbed in the `source/styles.jsx` and then css can be avoided in static compilation step..

**Comment by elseloop** [comment]
@krambuhl Doesn't that break with our focused proximity of concerns component model?

**Comment by krambuhl** [comment]
@elseloop yes and no.  It does (sort of) change where files are being included from (an index jsx file instead of each component), but does not change where actual files are located.  The reason I say sort of, is that we are already including css from a central index  (https://github.com/connectivedx/fuzzy-chainsaw/blob/develop/source/styles.jsx), this would just remove imports inside individual components

**Comment by elseloop** [comment]
@krambuhl oh, ok, so in authoring components, you wouldn't ever need to leave the component to include your styles, they're just compiled automagically. I missed that. Carry on.

**Comment by pgregorova** [comment]
Since I am still trying to get a hang of JSX, I've been trying to figure out how we handle headings. Right now we have a matching headline level class but what if for accessibility and semantic sake, I want what normally would look like h5 to be h2.  

So for instance, I could  set separately what a heading level should be as well as class to get something like this:
`<h2 class="heading--h5">Heading</h2>`
`<h3 class="heading--h3">Another Heading</h3>`

Another thing I am still trying to resolve is to load myfonts via JS that I am provided with, as it seems to perform way better than relying on CSS. If it helps, attaching the actual files, so you can have an actual example to play with. 
[myfonts-css.zip](https://github.com/connectivedx/fuzzy-chainsaw/files/663707/myfonts-css.zip)

**Comment by elseloop** [comment]
@pgregorova If I'm understanding your first point correctly, I have good news: you can already do that. 😄 When defining a `<Heading>` component, you can pass in both the `tagName` and `level` props:

```
<Heading tagName='h2' level='4'>Stuff</Heading>
```

`tagName` defines the actual HTML tag that's rendered (an `<h2>` here) and `level` is added to the `heading--{level}` class, giving you the result you're after. So, that example will output the following markup:

```
<h2 class="heading heading--default heading--h4 ">Stuff</h2>
```

For the example you provided, you'd want to compose the h2 like

```
<Heading tagName='h2' level='5'>Heading</Heading>
```

Is this what you were after?

**Comment by stoff** [comment]
Relating to PascalCase, #70, and #80:
renaming all source folders (tags, components, pages, styleguide) to use initial caps would better align with this convention, and prevent Webpack some confusion when FC integrates with LP.

Specifically, given an LP project with FC integrated, someone may set up an example page for specific components (to demonstrate a composed page).  when they `import`, if they correctly path to a given component, they will write something like `import ComponentName from '../Components/ComponentName/ComponentName'`; however Webpack also sees a reference (from the styleguide build) to `../components/ComponentName/ComponentName` and will believe that there are 2 matching components. It will throw multiple warnings for the "duplicate" component.  It otherwise completes normally, but the log could get very messy (and alarming for someone who doesn't know what's happening) very quickly.

I discussed this with @elseloop and he raised the point that simply capitalizing these folders both solves the issue and stays inline with Babel PascalCase naming conventions.

**Comment by krambuhl** [comment]
@stoff I don't understand the issue.. where is a capitalized `Components/` come from? is that LP specific?  

I don't like the idea of making changes on a JS project to use C# naming patterns on folders as well.  the reason for PascalCase is components are object definitions which are normally Uppercased in JS.  We should avoid making changes for integrating with "X" that are not universally needed.

**Comment by stoff** [comment]
the issue comes out of LP - essentially this comes out of a conversation I just had with @elseloop asking him to use lowercase `components/` even tho that doesn't match what's in the file system.

**Comment by elseloop** [comment]
@krambuhl @stoff I didn't realize the Components/components mismatch was from LP. I thought that was consistent in both but the references were inconsistent. I take back changing it here, as it no longer makes the same sense I had in my head before.

Ugh.

**Comment by krambuhl** [comment]
@stoff and I just talked, it might make sense for naming to be handled by a post FC integration script in LP that could replace instances of `/component/*` with `/Component/*`

**Comment by elseloop** [comment]
This was pointed out to me by @kamsar but definitely articulates a minor frustration I've had as well: it would be helpful for the styleguide menu (the one on the side when on a single tag/component page) to both include Pages ~~and to be ordered in a more helpfully hierarchical way (Pages => Components => Tags, rather than Tags => Components). This puts the pieces most frequently to be looked at not by the people who authored them at the top of the list, making them easier to surface for review, handoff, etc.~~ 🎈 Ok, cool, looks like @nicmarson already handled at least some of this with his redesign work, which seems to have moved Components above Tags. (Or that happened elsewhere? Point is: that now exists and 👏 to that). Getting pages in there would still be a bonus.

**Comment by krambuhl** [comment]
@elseloop All the code is there to handle page indexes as well, just needs to be added to `/source/styleguide/tags/Nav/Nav.jsx` like is already in `https://github.com/connectivedx/fuzzy-chainsaw/blob/develop/source/pages/index.jsx`  It be an easy add if you want it on your project before FC makes it official.

**Comment by elseloop** [comment]
Awesome. Thanks, @krambuhl! Do you wanna handle adding it here or would a PR for that be helpful? (Not sure if it's already on one of your longer running branches or in a later milestone or something...)

**Comment by krambuhl** [comment]
PR away! 🚀

**Comment by krambuhl** [comment]
Closing this issue for now. We will open the door again for feedback after a FC2 release.
