### ISSUE TITLE
Duplicate build command (full:production)

### ISSUE THREAD

**Issue by bstaruk** [connectivedx/fuzzy-chainsaw#277]
Some changes were made to the build commands with the [v2.1.0 patch](https://github.com/connectivedx/fuzzy-chainsaw/pull/276) which resulted in a duplicate command being left as a relic to prevent breaking backward compatibility.

This issue is here to serve as a reminder to remove this duplicate command (`full:production`) as part of the v3.0 release.

**Comment by drolsen** [comment]
We have confirmed that no PDX or Boston projects are using these duplicate commands.
Kam has also confirmed the lp is not using these as well.

We can either phase or cut these.
I say get rid of them sooner rather than later; before they (for whatever kind of crazy reason) do become a dependency on someones project(s).

**Comment by bstaruk** [comment]
The only reason I suggest leaving the extra command in is that if we don't, we'll need to make this a major version upgrade (3.0).

We don't use the command ourselves, but others might :)
