### ISSUE TITLE
Media query combining

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#88]
Back in the day we used a now-defunct gulp plugin to combine the identical media queries that were emitted by our sass mixins. It could save near 30% on file size sometimes.

Is that still a major issue with using just PostCSS? I noticed this plugin exists to combine queries, if it is:
https://github.com/hail2u/node-css-mqpacker

**Comment by krambuhl** [comment]
Because of the where the step in compiled that postcss fits, using mqpacker via the postcss-pack.js would be useless.  component css files are processed by postcss individually before being concatenated together.  If we need something to run on the output css files, gulp is our friend (slash, I've not figured out how to handle this via webpack)

**Comment by krambuhl** [comment]
Not that we are post postcss processing we can implement this feature via webpack. Going to add this to my next improvement branch.
