### ISSUE TITLE
How does one handle client-side JS related to a component?

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#89]
In #60 it was mentioned that `bundle.js` was being generated off `main.jsx`. This is true, and when removing the React code from `main.jsx` the bundle file goes to 2kb.

However I realized that there is no current sample of using JS with any components or tags. Sure they're written in JS but what if they use browser JS, not JSX->HTML JS.

![image](https://cloud.githubusercontent.com/assets/103677/20035467/cf49f0f4-a3a2-11e6-8aaa-24df2f3612b1.png)

## Expected Behavior

There needs to be a setup to bundle together scripts that are client-side for components (probably less so for tags).

## Possible Solution

It seems like a similar setup to `style.jsx` would be appropriate where it requires all `.js` files from components and tags would work well here. Removing the test React code from `main.jsx` would also be good.

## Secondary Notes

It's confusing that the root files in source (a) map to differently named output files and (b) though they have jsx extensions, are not all jsx.

I would like to propose:
1) Renaming `main.jsx` to `scripts.js`
2) Renaming `style.jsx` to `styles.js`
3) Renaming `tests.jsx` to `tests.js`
4) Renaming `styleguide.jsx` to `styleguide-scripts.js`, and/or possibly moving it under `/styleguide`
5) Renaming the output `bundle.css` and `bundle.js` to match their entry point files (e.g. `scripts.js` and `styles.css`)
6) Consider moving RenderPage.jsx under /pages and RenderStyleguide.jsx under /styleguide

**Comment by krambuhl** [comment]
The current behavior of having react pick up the front end requires sitecore either output initial state in json for that component or output the components `data-reactid` tags. I'm not sure how possible it is for us to build those data tags.

Currently if you want interactive ui, you'd build javascript out in a standard commonjs. We can't make use of react in the browser without blowing away state.

**Secondary notes:**

1. 👎 if you need to start a react application/component from this entry point, it would require that you update this file to jsx anyways. Seems like a reasonable use-case.
2. 👍 
3. 👍 
4. 👎 This is not just scripts, this also creates the styleguide css file. (also, see #6) Renaming to `.js` instead of `.jsx` is good.
5. 👍 
6. 🎱  Everything at this level is an entry file for webpack.  I prefer this consistency.  I can see new developers being confused by those files.  the `RenderStyleguide.jsx` and`styleguide.jsx` files are easy enough to hide away into the `styleguide` directory, but moving the `RenderPages.jsx` to the pages folder would only change where the confusion is coming from ("why does `/pages/RenderPages.jsx` not behave like  `/pages/index.jsx`?)

**Comment by krambuhl** [comment]
Most of these concerns are no longer relevant and/or have been resolved by changes in the `2.0` branch.  Closing.
